# here characters are the key and morse codes are the values
MORSE_CODES = { # should be used to encode
    # Characters : Morse Codes
    " " : "   ",
    "A" : ".-",
    "B" : "-...",
    "C" : "-.-.",
    "D" : "-..",
    "E" : ".",
    "F" : "..-.",
    "G" : "--.",
    "H" : "....",
    "I" : "..",
    "J" : ".---",
    "K" : "-.-",
    "L" : ".-..",
    "M" : "--",
    "N" : "-.",
    "O" : "---",
    "P" : ".--.",
    "Q" : "--.-",
    "R" : ".-.",
    "S" : "...",
    "T" : "-",
    "U" : "..-",
    "V" : "...-",
    "W" : ".--",
    "X" : "-..-",
    "Y" : "-.--",
    "Z" : "--..",
    "0" : "-----",
    "1" : ".----",
    "2" : "..---",
    "3" : "...--",
    "4" : "....-",
    "5" : ".....",
    "6" : "-....",
    "7" : "--...",
    "8" : "---..",
    "9" : "----.",
    "." : ".-.-.-",
    "," : "--..--",
    "?" : "..--..",
    "'" : ".----.",
    "!" : "-.-.--",
    "/" : "-..-.",
    "(" : "-.--.",
    ")" : "-.--.-",
    "&" : ".-...",
    ":" : "---...",
    ";" : "-.-.-.",
    "=" : "-...-",
    "+" : ".-.-.",
    "-" : "-....-",
    "_" : "..--.-",
    '"' : ".-..-.",
    "$" : "...-..-",
    "@" : ".--.-.",
}

# here morse codes are the key and characters are values
REVERSE_MORSE_CODES = { # should be used to decode
    # Morse Codes : Characters
}

for char, code in MORSE_CODES.items():
    REVERSE_MORSE_CODES[code] = char
